package com.finace.biz.domain;

import java.util.Date;

/**
 * 数据字典（表：data_dictionary）
 *
 * @author finace
 * @date 2024-03-07 22:45:28
 */
public class DataDictionary {
    /**
     *
     */
    private Long id;

    /**
     * 数据类型分类编码
     */
    private String dataCodeCate;

    /**
     * 数据编码
     */
    private String dataCode;

    /**
     * 数据值
     */
    private String dataValue;

    /**
     * 数据字典顺序
     */
    private Integer dataSort;

    /**
     * 是否禁用
     */
    private Boolean disable;

    /**
     * 创建时间
     */
    private Date createTime;

    /**
     * 修改时间
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_dictionary.id
     *
     * @return the value of data_dictionary.id
     * @mbg.generated Thu Mar 07 22:45:28 HKT 2024
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_dictionary.id
     *
     * @param id the value for data_dictionary.id
     * @mbg.generated Thu Mar 07 22:45:28 HKT 2024
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_dictionary.data_code_cate
     *
     * @return the value of data_dictionary.data_code_cate
     * @mbg.generated Thu Mar 07 22:45:28 HKT 2024
     */
    public String getDataCodeCate() {
        return dataCodeCate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_dictionary.data_code_cate
     *
     * @param dataCodeCate the value for data_dictionary.data_code_cate
     * @mbg.generated Thu Mar 07 22:45:28 HKT 2024
     */
    public void setDataCodeCate(String dataCodeCate) {
        this.dataCodeCate = dataCodeCate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_dictionary.data_code
     *
     * @return the value of data_dictionary.data_code
     * @mbg.generated Thu Mar 07 22:45:28 HKT 2024
     */
    public String getDataCode() {
        return dataCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_dictionary.data_code
     *
     * @param dataCode the value for data_dictionary.data_code
     * @mbg.generated Thu Mar 07 22:45:28 HKT 2024
     */
    public void setDataCode(String dataCode) {
        this.dataCode = dataCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_dictionary.data_value
     *
     * @return the value of data_dictionary.data_value
     * @mbg.generated Thu Mar 07 22:45:28 HKT 2024
     */
    public String getDataValue() {
        return dataValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_dictionary.data_value
     *
     * @param dataValue the value for data_dictionary.data_value
     * @mbg.generated Thu Mar 07 22:45:28 HKT 2024
     */
    public void setDataValue(String dataValue) {
        this.dataValue = dataValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_dictionary.data_sort
     *
     * @return the value of data_dictionary.data_sort
     * @mbg.generated Thu Mar 07 22:45:28 HKT 2024
     */
    public Integer getDataSort() {
        return dataSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_dictionary.data_sort
     *
     * @param dataSort the value for data_dictionary.data_sort
     * @mbg.generated Thu Mar 07 22:45:28 HKT 2024
     */
    public void setDataSort(Integer dataSort) {
        this.dataSort = dataSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_dictionary.disable
     *
     * @return the value of data_dictionary.disable
     * @mbg.generated Thu Mar 07 22:45:28 HKT 2024
     */
    public Boolean getDisable() {
        return disable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_dictionary.disable
     *
     * @param disable the value for data_dictionary.disable
     * @mbg.generated Thu Mar 07 22:45:28 HKT 2024
     */
    public void setDisable(Boolean disable) {
        this.disable = disable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_dictionary.create_time
     *
     * @return the value of data_dictionary.create_time
     * @mbg.generated Thu Mar 07 22:45:28 HKT 2024
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_dictionary.create_time
     *
     * @param createTime the value for data_dictionary.create_time
     * @mbg.generated Thu Mar 07 22:45:28 HKT 2024
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_dictionary.update_time
     *
     * @return the value of data_dictionary.update_time
     * @mbg.generated Thu Mar 07 22:45:28 HKT 2024
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_dictionary.update_time
     *
     * @param updateTime the value for data_dictionary.update_time
     * @mbg.generated Thu Mar 07 22:45:28 HKT 2024
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public void initDefault() {
        if (this.getDataCodeCate() == null) {
            this.setDataCodeCate("");
        }
        if (this.getDataCode() == null) {
            this.setDataCode("");
        }
        if (this.getDataValue() == null) {
            this.setDataValue("");
        }
        if (this.getDataSort() == null) {
            this.setDataSort(0);
        }
        if (this.getDisable() == null) {
            this.setDisable(false);
        }
        if (this.getCreateTime() == null) {
            this.setCreateTime(new Date());
        }
        if (this.getUpdateTime() == null) {
            this.setUpdateTime(new Date());
        }
    }

    public void initUpdate() {
    }
}