package com.finace.biz.domain;

import java.util.Date;

/**
 * 系统菜单（表：sys_menu）
 *
 * @author finace
 * @date 2024-03-07 22:45:28
 */
public class SysMenu {
    /**
     *
     */
    private Integer id;

    /**
     * 父级菜单
     */
    private Integer pid;

    /**
     * 菜单名称
     */
    private String name;

    /**
     * 菜单路由
     */
    private String path;

    /**
     * 菜单组件
     */
    private String component;

    /**
     * 图标
     */
    private String icon;

    /**
     * 是否使用布局
     */
    private Boolean layout;

    /**
     * 是否隐藏菜单
     */
    private Boolean hideInMenu;

    /**
     * 重定向地址
     */
    private String redirect;

    /**
     * 排序
     */
    private Integer sort;

    /**
     * 创建时间
     */
    private Date createTime;

    /**
     * 修改时间
     */
    private Date updateTime;

    /**
     * 用户id
     */
    private Long memberId;

    /**
     * 修改用户id
     */
    private Long updateMemberId;

    /**
     * 是否删除，0：删除，1：未删除
     */
    private Boolean delFlag;

    /**
     * 是否禁用
     */
    private Boolean disable;

    /**
     * 节点深度，0表示一级节点
     */
    private Integer nodePath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.id
     *
     * @return the value of sys_menu.id
     * @mbg.generated Thu Mar 07 22:45:28 HKT 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.id
     *
     * @param id the value for sys_menu.id
     * @mbg.generated Thu Mar 07 22:45:28 HKT 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.pid
     *
     * @return the value of sys_menu.pid
     * @mbg.generated Thu Mar 07 22:45:28 HKT 2024
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.pid
     *
     * @param pid the value for sys_menu.pid
     * @mbg.generated Thu Mar 07 22:45:28 HKT 2024
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.name
     *
     * @return the value of sys_menu.name
     * @mbg.generated Thu Mar 07 22:45:28 HKT 2024
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.name
     *
     * @param name the value for sys_menu.name
     * @mbg.generated Thu Mar 07 22:45:28 HKT 2024
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.path
     *
     * @return the value of sys_menu.path
     * @mbg.generated Thu Mar 07 22:45:28 HKT 2024
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.path
     *
     * @param path the value for sys_menu.path
     * @mbg.generated Thu Mar 07 22:45:28 HKT 2024
     */
    public void setPath(String path) {
        this.path = path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.component
     *
     * @return the value of sys_menu.component
     * @mbg.generated Thu Mar 07 22:45:28 HKT 2024
     */
    public String getComponent() {
        return component;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.component
     *
     * @param component the value for sys_menu.component
     * @mbg.generated Thu Mar 07 22:45:28 HKT 2024
     */
    public void setComponent(String component) {
        this.component = component;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.icon
     *
     * @return the value of sys_menu.icon
     * @mbg.generated Thu Mar 07 22:45:28 HKT 2024
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.icon
     *
     * @param icon the value for sys_menu.icon
     * @mbg.generated Thu Mar 07 22:45:28 HKT 2024
     */
    public void setIcon(String icon) {
        this.icon = icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.layout
     *
     * @return the value of sys_menu.layout
     * @mbg.generated Thu Mar 07 22:45:28 HKT 2024
     */
    public Boolean getLayout() {
        return layout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.layout
     *
     * @param layout the value for sys_menu.layout
     * @mbg.generated Thu Mar 07 22:45:28 HKT 2024
     */
    public void setLayout(Boolean layout) {
        this.layout = layout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.hide_in_menu
     *
     * @return the value of sys_menu.hide_in_menu
     * @mbg.generated Thu Mar 07 22:45:28 HKT 2024
     */
    public Boolean getHideInMenu() {
        return hideInMenu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.hide_in_menu
     *
     * @param hideInMenu the value for sys_menu.hide_in_menu
     * @mbg.generated Thu Mar 07 22:45:28 HKT 2024
     */
    public void setHideInMenu(Boolean hideInMenu) {
        this.hideInMenu = hideInMenu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.redirect
     *
     * @return the value of sys_menu.redirect
     * @mbg.generated Thu Mar 07 22:45:28 HKT 2024
     */
    public String getRedirect() {
        return redirect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.redirect
     *
     * @param redirect the value for sys_menu.redirect
     * @mbg.generated Thu Mar 07 22:45:28 HKT 2024
     */
    public void setRedirect(String redirect) {
        this.redirect = redirect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.sort
     *
     * @return the value of sys_menu.sort
     * @mbg.generated Thu Mar 07 22:45:28 HKT 2024
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.sort
     *
     * @param sort the value for sys_menu.sort
     * @mbg.generated Thu Mar 07 22:45:28 HKT 2024
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.create_time
     *
     * @return the value of sys_menu.create_time
     * @mbg.generated Thu Mar 07 22:45:28 HKT 2024
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.create_time
     *
     * @param createTime the value for sys_menu.create_time
     * @mbg.generated Thu Mar 07 22:45:28 HKT 2024
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.update_time
     *
     * @return the value of sys_menu.update_time
     * @mbg.generated Thu Mar 07 22:45:28 HKT 2024
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.update_time
     *
     * @param updateTime the value for sys_menu.update_time
     * @mbg.generated Thu Mar 07 22:45:28 HKT 2024
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.member_id
     *
     * @return the value of sys_menu.member_id
     * @mbg.generated Thu Mar 07 22:45:28 HKT 2024
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.member_id
     *
     * @param memberId the value for sys_menu.member_id
     * @mbg.generated Thu Mar 07 22:45:28 HKT 2024
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.update_member_id
     *
     * @return the value of sys_menu.update_member_id
     * @mbg.generated Thu Mar 07 22:45:28 HKT 2024
     */
    public Long getUpdateMemberId() {
        return updateMemberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.update_member_id
     *
     * @param updateMemberId the value for sys_menu.update_member_id
     * @mbg.generated Thu Mar 07 22:45:28 HKT 2024
     */
    public void setUpdateMemberId(Long updateMemberId) {
        this.updateMemberId = updateMemberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.del_flag
     *
     * @return the value of sys_menu.del_flag
     * @mbg.generated Thu Mar 07 22:45:28 HKT 2024
     */
    public Boolean getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.del_flag
     *
     * @param delFlag the value for sys_menu.del_flag
     * @mbg.generated Thu Mar 07 22:45:28 HKT 2024
     */
    public void setDelFlag(Boolean delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.disable
     *
     * @return the value of sys_menu.disable
     * @mbg.generated Thu Mar 07 22:45:28 HKT 2024
     */
    public Boolean getDisable() {
        return disable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.disable
     *
     * @param disable the value for sys_menu.disable
     * @mbg.generated Thu Mar 07 22:45:28 HKT 2024
     */
    public void setDisable(Boolean disable) {
        this.disable = disable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.node_path
     *
     * @return the value of sys_menu.node_path
     * @mbg.generated Thu Mar 07 22:45:28 HKT 2024
     */
    public Integer getNodePath() {
        return nodePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.node_path
     *
     * @param nodePath the value for sys_menu.node_path
     * @mbg.generated Thu Mar 07 22:45:28 HKT 2024
     */
    public void setNodePath(Integer nodePath) {
        this.nodePath = nodePath;
    }

    public void initDefault() {
        if (this.getPid() == null) {
            this.setPid(0);
        }
        if (this.getName() == null) {
            this.setName("");
        }
        if (this.getPath() == null) {
            this.setPath("");
        }
        if (this.getComponent() == null) {
            this.setComponent("");
        }
        if (this.getIcon() == null) {
            this.setIcon("");
        }
        if (this.getLayout() == null) {
            this.setLayout(false);
        }
        if (this.getHideInMenu() == null) {
            this.setHideInMenu(false);
        }
        if (this.getRedirect() == null) {
            this.setRedirect("");
        }
        if (this.getSort() == null) {
            this.setSort(0);
        }
        if (this.getCreateTime() == null) {
            this.setCreateTime(new Date());
        }
        if (this.getUpdateTime() == null) {
            this.setUpdateTime(new Date());
        }
        if (this.getMemberId() == null) {
            this.setMemberId(0L);
        }
        if (this.getUpdateMemberId() == null) {
            this.setUpdateMemberId(0L);
        }
        if (this.getDelFlag() == null) {
            this.setDelFlag(false);
        }
        if (this.getDisable() == null) {
            this.setDisable(false);
        }
        if (this.getNodePath() == null) {
            this.setNodePath(0);
        }
    }

    public void initUpdate() {
    }
}