package com.finace.biz.domain;

import java.util.Date;

/**
 * 系统资源（表：sys_resource）
 *
 * @author finace
 * @date 2024-03-07 22:45:28
 */
public class SysResource {
    /**
     *
     */
    private Integer id;

    /**
     * 父id
     */
    private Integer pid;

    /**
     * 资源名称
     */
    private String name;

    /**
     * 资源路径
     */
    private String path;

    /**
     * 排序
     */
    private Integer sort;

    /**
     * 创建时间
     */
    private Date createTime;

    /**
     * 修改时间
     */
    private Date updateTime;

    /**
     * 用户id
     */
    private Long memberId;

    /**
     * 修改用户id
     */
    private Long updateMemberId;

    /**
     * 是否删除，0：删除，1：未删除
     */
    private Boolean delFlag;

    /**
     * 是否禁用
     */
    private Boolean disable;

    /**
     * 节点深度
     */
    private Integer nodePath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.id
     *
     * @return the value of sys_resource.id
     * @mbg.generated Thu Mar 07 22:45:28 HKT 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.id
     *
     * @param id the value for sys_resource.id
     * @mbg.generated Thu Mar 07 22:45:28 HKT 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.pid
     *
     * @return the value of sys_resource.pid
     * @mbg.generated Thu Mar 07 22:45:28 HKT 2024
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.pid
     *
     * @param pid the value for sys_resource.pid
     * @mbg.generated Thu Mar 07 22:45:28 HKT 2024
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.name
     *
     * @return the value of sys_resource.name
     * @mbg.generated Thu Mar 07 22:45:28 HKT 2024
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.name
     *
     * @param name the value for sys_resource.name
     * @mbg.generated Thu Mar 07 22:45:28 HKT 2024
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.path
     *
     * @return the value of sys_resource.path
     * @mbg.generated Thu Mar 07 22:45:28 HKT 2024
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.path
     *
     * @param path the value for sys_resource.path
     * @mbg.generated Thu Mar 07 22:45:28 HKT 2024
     */
    public void setPath(String path) {
        this.path = path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.sort
     *
     * @return the value of sys_resource.sort
     * @mbg.generated Thu Mar 07 22:45:28 HKT 2024
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.sort
     *
     * @param sort the value for sys_resource.sort
     * @mbg.generated Thu Mar 07 22:45:28 HKT 2024
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.create_time
     *
     * @return the value of sys_resource.create_time
     * @mbg.generated Thu Mar 07 22:45:28 HKT 2024
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.create_time
     *
     * @param createTime the value for sys_resource.create_time
     * @mbg.generated Thu Mar 07 22:45:28 HKT 2024
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.update_time
     *
     * @return the value of sys_resource.update_time
     * @mbg.generated Thu Mar 07 22:45:28 HKT 2024
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.update_time
     *
     * @param updateTime the value for sys_resource.update_time
     * @mbg.generated Thu Mar 07 22:45:28 HKT 2024
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.member_id
     *
     * @return the value of sys_resource.member_id
     * @mbg.generated Thu Mar 07 22:45:28 HKT 2024
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.member_id
     *
     * @param memberId the value for sys_resource.member_id
     * @mbg.generated Thu Mar 07 22:45:28 HKT 2024
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.update_member_id
     *
     * @return the value of sys_resource.update_member_id
     * @mbg.generated Thu Mar 07 22:45:28 HKT 2024
     */
    public Long getUpdateMemberId() {
        return updateMemberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.update_member_id
     *
     * @param updateMemberId the value for sys_resource.update_member_id
     * @mbg.generated Thu Mar 07 22:45:28 HKT 2024
     */
    public void setUpdateMemberId(Long updateMemberId) {
        this.updateMemberId = updateMemberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.del_flag
     *
     * @return the value of sys_resource.del_flag
     * @mbg.generated Thu Mar 07 22:45:28 HKT 2024
     */
    public Boolean getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.del_flag
     *
     * @param delFlag the value for sys_resource.del_flag
     * @mbg.generated Thu Mar 07 22:45:28 HKT 2024
     */
    public void setDelFlag(Boolean delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.disable
     *
     * @return the value of sys_resource.disable
     * @mbg.generated Thu Mar 07 22:45:28 HKT 2024
     */
    public Boolean getDisable() {
        return disable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.disable
     *
     * @param disable the value for sys_resource.disable
     * @mbg.generated Thu Mar 07 22:45:28 HKT 2024
     */
    public void setDisable(Boolean disable) {
        this.disable = disable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.node_path
     *
     * @return the value of sys_resource.node_path
     * @mbg.generated Thu Mar 07 22:45:28 HKT 2024
     */
    public Integer getNodePath() {
        return nodePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.node_path
     *
     * @param nodePath the value for sys_resource.node_path
     * @mbg.generated Thu Mar 07 22:45:28 HKT 2024
     */
    public void setNodePath(Integer nodePath) {
        this.nodePath = nodePath;
    }

    public void initDefault() {
        if (this.getPid() == null) {
            this.setPid(0);
        }
        if (this.getName() == null) {
            this.setName("");
        }
        if (this.getPath() == null) {
            this.setPath("");
        }
        if (this.getSort() == null) {
            this.setSort(0);
        }
        if (this.getCreateTime() == null) {
            this.setCreateTime(new Date());
        }
        if (this.getUpdateTime() == null) {
            this.setUpdateTime(new Date());
        }
        if (this.getMemberId() == null) {
            this.setMemberId(0L);
        }
        if (this.getUpdateMemberId() == null) {
            this.setUpdateMemberId(0L);
        }
        if (this.getDelFlag() == null) {
            this.setDelFlag(false);
        }
        if (this.getDisable() == null) {
            this.setDisable(false);
        }
        if (this.getNodePath() == null) {
            this.setNodePath(0);
        }
    }

    public void initUpdate() {
    }
}